packages:
  - "apps/*"
  - "packages/*"
  - "tools/*"

catalog:
  "@types/node": ^22.13.9
  eslint: ^9.21.0
  prettier: ^3.5.3
  typescript: ^5.8.2

catalogs:
  next-15:
    next: ^15.2.1
  react-19:
    "@types/react": ^19.0.10
    "@types/react-dom": ^19.0.4
    react: ^19.0.0
    react-dom: ^19.0.0
